---
title: "MSDS6372 - Final Project"
author: "Benjamin Wilke, Michael Landrum"
date: "March 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# required libraries
library(kableExtra) # to make uber sexy tables for output
library(pastecs) # for easy descriptive statistics
library(ggbiplot) # implementation of biplot using ggplot2 for plotting PCs
library(Amelia) # cool library for exploring missing data

# turn off scientfic notation for the entire script
options(scipen = 999)

```

## Introduction


## Exploratory Data Analysis

```{r, echo=TRUE}
# import the data
BBHOFRaw <- read.table("MLBHOF-tab.new.dat.txt", sep="\t", header=FALSE)

# create column names
colnames(BBHOFRaw) <- c("Name", "NumSeasonsPlayed", "GamesPlayed", "OfficialAtBats", "RunsScored", "Hits", "Doubles", "Triples", "HomeRuns", "RunsBattedIn", "Walks", "Strikeouts", "BattingAvg", "OnBasePct", "SluggingPct", "AdjustedProduction", "BattingRuns", "AdjustedBattingRuns", "RunsCreated", "StolenBases", "CaughtStealing", "StolenBaseRuns", "FieldingAvg", "FieldingRuns", "PrimaryPositionPlayed", "TotalPlayerRating", "HOFMembership")

# fix some import typecasting issues and apply NA null for values with "."
BBHOFRaw$Name <- as.character(BBHOFRaw$Name)

BBHOFRaw$Strikeouts[BBHOFRaw$Strikeouts == "."] <- NA
BBHOFRaw$Strikeouts <- as.integer(BBHOFRaw$Strikeouts)

BBHOFRaw$StolenBases[BBHOFRaw$StolenBases == "."] <- NA
BBHOFRaw$StolenBases <- as.integer(BBHOFRaw$StolenBases)

BBHOFRaw$CaughtStealing[BBHOFRaw$CaughtStealing == "."] <- NA
BBHOFRaw$CaughtStealing <- as.integer(BBHOFRaw$CaughtStealing)

BBHOFRaw$StolenBaseRuns[BBHOFRaw$StolenBaseRuns == "."] <- NA
BBHOFRaw$StolenBaseRuns <- as.integer(BBHOFRaw$StolenBaseRuns)

# display top 5 observations
knitr::kable(BBHOFRaw[1:5,],caption = "Top 10 Observations from Baseball Hall of Fame Data", row.names = FALSE, "html") %>%
  kable_styling(bootstrap_options = c("striped","hover"))



```


```{r, echo=TRUE, fig.width=8, fig.height=10}
# display missing values
missmap(BBHOFRaw, main="Missing Values in Raw Data")


```


```{r, echo=TRUE}
# display frequency table for did/did not get inducted into HOF
# since the labels also include 2, converting those to 1, so the result is truly binary (1, 0)
BBHOFRaw$HOFMembership[BBHOFRaw$HOFMembership == 2] <- 1
count(BBHOFRaw, "HOFMembership")

# descriptive statistics, load into new data frame for processing
descriptiveTable <- stat.desc(BBHOFRaw)

# remove non-numeric features
dropcolumns <- c("Name","PrimaryPositionPlayed", "HOFMembership")
descriptiveTable <- descriptiveTable[,!(colnames(descriptiveTable) %in% dropcolumns)]

# round all numeric values to 2 decimal points
descriptiveTable <- round(descriptiveTable, 2)

# remove rows for statistics we don't care about, leaving: N, Mean, Median, Std Dev, Var, Min, Max
remove <- c("nbr.null", "nbr.na", "range", "sum", "SE.mean", "CI.mean", "coef.var")
descriptiveTable <- descriptiveTable[-which(rownames(descriptiveTable) %in% remove),]

# display descriptive statistics
knitr::kable(descriptiveTable,caption = "Descriptive Statistics for Numeric Features in the Baseball Hall of Fame Data", row.names = TRUE, "html") %>%
  kable_styling(bootstrap_options = c("striped","hover", "condensed", "responsive"))

```



```{r echo=TRUE}

# remove non-numeric features and features with missing values (NEED TO REVISIT THIS)
dropcolumnsPCA <- c("Name", "PrimaryPositionPlayed", "HOFMembership", "Strikeouts", "StolenBases", "CaughtStealing", "StolenBaseRuns")
BBHOF_PCA <- BBHOFRaw[,!(colnames(BBHOFRaw) %in% dropcolumnsPCA)]

# extract labels (player made it into HOF), convert to factor
BBHOF_Labels_PCA <- BBHOFRaw["HOFMembership"]
BBHOF_Labels_PCA$HOFMembership <- as.factor(BBHOF_Labels_PCA$HOFMembership)

# perform PCA
BBHOF_PCA <- prcomp(BBHOF_PCA, center=TRUE, scale.=TRUE)

# print principal components (only the first 4 PCs)
print(BBHOF_PCA$rotation[,1:4])

# summary of principal components
summary(BBHOF_PCA)


```

```{r, echo=TRUE, fig.width=15, fig.height=10}
# plot PCs using ggbiplot
ggbiplot(BBHOF_PCA, obs.scale=1, var.scale=1, groups=BBHOF_Labels_PCA$HOFMembership, ellipse=TRUE, circle=TRUE) + theme(legend.position='top') + scale_color_discrete()

```

alright....working some logistic regression..

```{r, echo=TRUE}

# copy data set, remove Name from the raw data set, so it's not included in the model, also removing features to play with the model
BBHOF_logistic <- BBHOFRaw
dropcolumns <- c("Name", "StolenBaseRuns", "StrikeOuts", "CaughtStealing", "StolenBases")
BBHOF_logistic <- BBHOF_logistic[,!(colnames(BBHOF_logistic) %in% dropcolumns)]

# split the raw data into testing and training data
set.seed(100) # set seed so that same sample can be reproduced in future

# now selecting 90% of data as sample from total 'n' rows of the data  
sample <- sample.int(n=nrow(BBHOF_logistic), size=floor(.90*nrow(BBHOF_logistic)), replace=FALSE)

# subset the data using the sample integer vector created above
train <- BBHOF_logistic[sample, ]
test  <- BBHOF_logistic[-sample, ]

# fitting the binomial logistic regression model, HOFMembership is dependent, fitting using all features
model <- glm(train$HOFMembership ~., family=binomial(link='logit'),data=train)

summary(model)

# predict based on the test data, type='response' output probabilities in the form of P(y=1|X)
fittedresults <- predict(model, newdata=test, type='response')

# there are some NAs in the fitted results...we need to check into that - not sure how that's possible if I'm removing the features with NAs
sum(is.na(fittedresults))

# if P(y=1|X) > 0.5 then y = 1 otherwise y=0
fittedresults <- ifelse(fittedresults > 0.5, 1, 0)

# calculate the mean of the fitted results that don't equal the observed result - IGNORE NAs
misClasificError <- mean(fittedresults != test$HOFMembership, na.rm=TRUE)

# print the output as 100% - error
print(paste('Accuracy',1-misClasificError))


```




